# Name of website
title: Meetings on Computations

logo: /assets/img/logo.png

description: 

navbar-links:
  About Me: "about"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"



# show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal


plugins:
  - jekyll-paginate
  - jekyll-sitemap
