# Name of website
title: Meetings on Computations

logo: /assets/img/logo.png

description: 

navbar-links:
  About Me: "about"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"



# show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal



# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "Europe/Oslo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
